### ISSUE TITLE
How to use the generated grammar in eclipse

### ISSUE THREAD

**Issue by ekrisza** [jknack/antlr4ide#103]
Hi,

Could you help with some help on how to make the ANTLRv4 generated parser work inside eclipse, inside a plugin?

I'm converting a project that is based on antlrv2 to antlrv4 ... but I'm stuck at executing the generated code, and need some help to be able to continue.

What I'm doing:
- antlr4ide.core is set as a dependency of my plugin.
- The grammar is in ANTLR v4 format inside my plugin.
- I use antlr4ide configured to generate the code right into the src folder.
- All java files are generated correctly, there are no java errors either.
- When I try to execute the code I get the following exception /*lines refering the my own code removed */
  "java.lang.NoClassDefFoundError: org/antlr/v4/runtime/CharStream
  ...
  Caused by: java.lang.ClassNotFoundException: org.antlr.v4.runtime.CharStream
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 9 more
  "

I have also tried to copy the antlr-4.4-complete.jar into the root of my plugin project; set it as a library on the build path (in eclipse project settings). Also tried to set it is exported.

The import is prefectly fine in the java file. Eclispe does not report any kind of error on it.
/*if I don't have antlr4ide installed, or corrupt one of the org.entlr.v4.runtime imports in the file, java notices it correctly ... so the Java check is in effect. */

How could I make eclipse find that class, when I run my plugin through a launch configuration?

**Comment by ekrisza** [comment]
I have also tried to generate a project with the ANTLR4 project wizard in the plugin.
The generated grammar compiles fine, without problems .... but I see no way to launch that project in eclipse to try it out as a plugin.

**Comment by ekrisza** [comment]
I found a work around: If I put the antlr-4.4-complet.jar in my plugin and add it to the bundle-classpath the classes are found, and execution runs fine.

I believe it would be much better if my plugin would only need to depend on the antlr4ide plugins, and get all the necessary classes from there.
Is there a way to do that ?

**Comment by ekrisza** [comment]
I believe this could be made possible with only editing the Manifest.MF in the core project/plugin.

Adding "lib/antlr-4.4-complete.jar" to the Bouldne-ClassPath part makes the jar visible externally.
Adding "org.antlr.v4.runtime,org.antlr.v4.runtime.misc,org.antlr.v4.runtime.atn,org.antlr.v4.runtime.dfa
" to the Export-Packae list makes classes in these packages accessible externally.

After this change it would be possible to compile/execute the generated Java files, without any other dependency, than the the antlr4ide plugin.

**Comment by arifogel** [comment]
Hi I just picked up this project. Do you need any changes made to antlr4ide to support what you are trying to do? Did you figure it out?

**Comment by HSorensen** [comment]
Why do you have dependencies on antlr4ide.core ?
Does your plugin generate code as well or are you just using the generated grammar within your plugin?

**Comment by KristofSzabados** [comment]
Hi, thank for getting back to this issue.

We managed to solve the issue, by using the antlr4 runtime from eclipse orbit.
That way the required classes are present in eclipse.

**Comment by HSorensen** [comment]
Closed.
