### ISSUE TITLE
Font color problem when using the Eclipse dark theme

### ISSUE THREAD

**Issue by kkeri** [jknack/antlr4ide#104]
I use Eclipse with the dark theme. When editing ANTLR grammars, syntax definition names appear in dark blue on a dark grey background, not quite readable. I haven't found any way to change it in Eclipse. Can you help me?

**Comment by jknack** [comment]
Hey,

 I have the same problem, but not sure how to fix it. I think this is an xText bug and/or the dark theme plugin.

**Comment by arifogel** [comment]
I also use a dark theme. I have been able to edit all colors using Window->Preferences->ANTLR 4->Syntax Coloring. Closing since invalid.
