### ISSUE TITLE
Lexer generated in wrong directory

### ISSUE THREAD

**Issue by pvc** [jknack/antlr4ide#105]
I'm just trying this plugin out, and think it is great! However I may have discovered a bug (my apologies if it us new user error!), which makes it difficult to work with separated grammars:

When using @header(package foo) in a parser grammar, Antlr is correctly called with option "-o path/foo", but in the case of a separate lexer grammar the generated option is "-o path/foo/foo", so that the lexer output is placed in directory foo/foo instead of foo.
Let me know if you need anything else to reproduce it.

**Comment by HSorensen** [comment]
See issue #121

**Comment by arifogel** [comment]
Closing since main activity is happening in #121.
