### ISSUE TITLE
when is "-package" used ?

### ISSUE THREAD

**Issue by ekrisza** [jknack/antlr4ide#107]
I have 4 grammar files.
According to the output out of the 4 only 1 gets the "-package" parameter when the compiler is called.
The only difference I see is that, that grammar has multiple lexical modes.

This is very strange.
In that file I had to delete the package declaration from the @header otherwise it was inserted in the generated code twice.
But the other 3 require the @header to contain the package declaration to compile.

How can I force the use/not-use of this parameter?

**Comment by HSorensen** [comment]
See issue #121

**Comment by arifogel** [comment]
Closing as probably fixed. See progress in #121 as @HSorensen suggested.
