### ISSUE TITLE
Incompatibility with Xtext 2.8

### ISSUE THREAD

**Issue by Endeavourl** [jknack/antlr4ide#110]
Xtext has recently pushed out the 2.8 Redistributable via auto-update. After installing it the antlr editor opens with ClassCastException.

Issue #102 is probably related to this.

**Comment by daxl70** [comment]
When is this expected to be fixed?

**Comment by lukeu** [comment]
It appears to have been a breaking-API change in XText 2.8.0, now resolved in XText 2.8.2:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=464016

It appears to work fine for me now after updating XText, so I think this ticket can be closed.

**Comment by Endeavourl** [comment]
Confirmed working with xtext 2.8.2.
