### ISSUE TITLE
Tool Preferences UI missing added jars

### ISSUE THREAD

**Issue by sailorpsy** [jknack/antlr4ide#113]
I've added the ANTLR 4.5 jar under the `ANTLR 4 > Tool` preferences, saved the changes, and the automatic code generation uses it. However, when I later re-open the preferences window, the added jar is missing. The default jar (v4.4) is all that shows up.

![prefs](https://cloud.githubusercontent.com/assets/8271665/6879474/539a0736-d4c4-11e4-8757-8e71dc0e9fea.png)

**Comment by renzet** [comment]
I think the preferences don't work well, see my issue with the 'Generate a parse tree listener' option #137

**Comment by arifogel** [comment]
This sounds like issue #128. I am closing as duplicate, since that one has more activity.
