### ISSUE TITLE
Package in header is ignored

### ISSUE THREAD

**Issue by amura11** [jknack/antlr4ide#121]
I created a simple grammar just to test a few things out. This is the header declaration:

```
@header {
    package grammar.test;
}
```

For my first few builds it worked fine and put the grammar files in `/target/generated-sources/antlr4/grammar/test` but then all of a sudden it started to place them in the default package. The `package` directive at the top of the generated sources is correct but the location is wrong.

**Comment by HSorensen** [comment]
I had the same problem. After some debugging and searching it seems to work. See [my fork](
https://github.com/HSorensen/antlr4ide/commit/7c1d4c0f9de75513f03b553abce35903b77d2b0d)

**Comment by arifogel** [comment]
@HSorensen I belive your commits have been merged. If this is fixed, please close this issue.

**Comment by HSorensen** [comment]
This has been fixed with version 0.3.7, if not please reopen this issue.
