### ISSUE TITLE
Antlr4 project does not have the Java nature

### ISSUE THREAD

**Issue by blancas** [jknack/antlr4ide#124]
New Project... ANTLR4 is listed under General.
Once created (in the wrong place for me, since I tried changing the location) it was not a Java project as well and thus nothing compiled.

**Comment by arifogel** [comment]
Hey I just picked up this project. Do you get the behavior you desire by creating a java project, adding a g4 file, and then trying to add the antlr/xtext nature?

**Comment by blancas** [comment]
Thanks for checking. I've just installed version `0.3.6.201611052310` and I can now create a new antlr4 project that runs fine and also convert a Java project by adding the xtext nature. It all works now.
