### ISSUE TITLE
allow use of variables in external tool config

### ISSUE THREAD

**Issue by bemace** [jknack/antlr4ide#126]
It should be possible to use Eclipse's [variables](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Fconcepts%2Fconcepts-exttools.htm) such as `${project_path}` when specifying the location of a grammar file

**Comment by arifogel** [comment]
Where?

**Comment by bemace** [comment]
We'd like project_path to define the path to the grammar file. As it stands
now, we have to hard code the entire path relative to the workspace root.
If someone checks out a copy of the project under a different name (as is
done for our official builds), it doesn't work, and we have to create a
second external tool config for it.

**Comment by arifogel** [comment]
No I mean in which UI element do you specify the location of a grammar file? I.e. what window, etc? I ask because I actually don't use the vast majority of the features of antlr4ide, and am still learning its full feature set. To help me help you:
1. Write up the full steps to get to your problem, and list both the desired behavior and actual behavior.
2. Screenshots will help.

**Comment by bemace** [comment]
under Run->External Tools->External Tools Configurations
right-click on ANTLR and select "New"
![external tool config screen](https://cloud.githubusercontent.com/assets/546341/20071307/9a58befa-a4e9-11e6-8c72-0cb6173530d5.PNG)


If you right-click "Program" and select "New" in the same screen, you'll see there's a "Variables" button that provides all sorts of options
![program external config](https://cloud.githubusercontent.com/assets/546341/20071358/d153821e-a4e9-11e6-930c-6b6e41727330.PNG)
 
If those variables were support in the grammar path we wouldn't have to create separate run configs for each copy of the project that's checked out

**Comment by arifogel** [comment]
Your request sounds reasonable. I'll look into this.

**Comment by HSorensen** [comment]
Fixed by pull request #155
