### ISSUE TITLE
Current Version of ANTLR is rejected

### ISSUE THREAD

**Issue by toKrause** [jknack/antlr4ide#129]
When trying to add the current version of ANTL, `antlr-4.5.1-complete.jar`, under Preferences -> ANTLR 4 -> Tool -> ANTLR Tool -> Add, the following error message pops up:

```
Invalid JAR: "/path/to/antlr-4.5.1-complete.jar"

Visit http://www.antlr.org/download.html and download the:
"Complete ANTLR 4.x Java binaries jar" distribution
```

I had to add the following entries to the `MANIFEST.MF` inside `antlr-4.5.1-complete.jar`:

```
Main-Class: org.antlr.v4.Tool
Implementation-Vendor: ANTLR
Implementation-Title: ANTLR 4 Tool
Implementation-Version: 4.5.1
```

These were in previous versions of ANTLR, but not in the current jar. According to the `Created-By` entry, the build tools where changed from `http://www.bildtool.org` to `Apache Maven 3.3.3`. Maybe thats why the `Implementation-*` entries are now missing. 

ANTLR IDE should disable the corresponding plausibility checks.

**Comment by arifogel** [comment]
Hey I just picked up this project. I'll look into this.

**Comment by HSorensen** [comment]
This is really a problem with ANTLR and not ANTLRIDE. So close this, and please open an issue with ANTLR project.

If you are building antlr yourselves you can update the antlr4/tool/pom.xml with:
`
       <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.6</version>
		<configuration>
			<archive>
				<manifest>
				 
				    <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
					<mainClass>org.antlr.v4.Tool</mainClass>
				</manifest>
			</archive>
		</configuration>
`
That will add the missing manifest attributes
