### ISSUE TITLE
Maven compilation with Java8

### ISSUE THREAD

**Issue by timeraider4u** [jknack/antlr4ide#151]
Tried to compile it with _mvn clean package_ and Oracle JDK 1.8.0.112. Fails because of https://github.com/jknack/antlr4ide/blob/master/pom.xml#L83
When the version range in maven-enforcer is adjusted to
`<version>[1.6.0,1.9.0)</version>` the JUnit tests in ANTLR v4 IDE Tests fail with `java.lang.IllegalStateException: Failed to transform class with name com.github.jknack.antlr4ide.validation.Antlr4Validator. Reason: java.io.IOException: invalid constant type: 18`. This seems to be similar to http://stackoverflow.com/questions/32854688/powermock-java-lang-illegalstateexception-failed-to-transform-class

Unfortunately, adjusting the powermock (e.g. to 1.6.5 as seen on https://mvnrepository.com/artifact/org.powermock/powermock-core) and javassist to org.javassist (e.g. to 3.22.0-CR1 as seen on https://mvnrepository.com/artifact/org.javassist/javassist/3.22.0-CR1) does not solve this problem. 

If anybody has an idea, just let me now. Otherwise I will try to investigate this problem when I have more time.

**Comment by arifogel** [comment]
I did everything you tried this week. I was unsuccessful getting to build with Java 8. I gave up, installed Java 7 alongside Java 8, set JAVA_HOME to use Java 7, and went on with my life. If you can fix this, you'll have my thanks.

**Comment by arifogel** [comment]
The furthest I got was undefined references to javassist.* (because it had been changed to org.javassist.*) with some package I don't remember - probably powermock. I tried updating every version of everything related, but could not get past this.

**Comment by arifogel** [comment]
By the way, remember to clean out old jar versions in between attempts.
You can use git clean -nxdf to list all untracked files, and git clean -xdf to remove them (or just remove them by hand).

**Comment by timeraider4u** [comment]
@arifogel: Thank you for your hints! I have created a pull request which seems to fix this problem, can you give it a try? Seems you have to adjust the version numbers in five different files... :-(
